package com.candy.basic.mapper;

import com.candy.basic.entity.BsSeller;
import java.util.List;

public interface BsSellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsseller
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long sellerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsseller
     *
     * @mbggenerated
     */
    int insert(BsSeller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsseller
     *
     * @mbggenerated
     */
    BsSeller selectByPrimaryKey(Long sellerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsseller
     *
     * @mbggenerated
     */
    List<BsSeller> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsseller
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BsSeller record);
}