package com.candy.basic.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class BsSeller implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsseller.seller_id
     *
     * @mbggenerated
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsseller.seller_name
     *
     * @mbggenerated
     */
    private String sellerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsseller.remaker_score
     *
     * @mbggenerated
     */
    private BigDecimal remakerScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsseller.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsseller.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bsseller
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsseller.seller_id
     *
     * @return the value of bsseller.seller_id
     *
     * @mbggenerated
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsseller.seller_id
     *
     * @param sellerId the value for bsseller.seller_id
     *
     * @mbggenerated
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsseller.seller_name
     *
     * @return the value of bsseller.seller_name
     *
     * @mbggenerated
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsseller.seller_name
     *
     * @param sellerName the value for bsseller.seller_name
     *
     * @mbggenerated
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName == null ? null : sellerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsseller.remaker_score
     *
     * @return the value of bsseller.remaker_score
     *
     * @mbggenerated
     */
    public BigDecimal getRemakerScore() {
        return remakerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsseller.remaker_score
     *
     * @param remakerScore the value for bsseller.remaker_score
     *
     * @mbggenerated
     */
    public void setRemakerScore(BigDecimal remakerScore) {
        this.remakerScore = remakerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsseller.create_date
     *
     * @return the value of bsseller.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsseller.create_date
     *
     * @param createDate the value for bsseller.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsseller.update_date
     *
     * @return the value of bsseller.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsseller.update_date
     *
     * @param updateDate the value for bsseller.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsseller
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sellerId=").append(sellerId);
        sb.append(", sellerName=").append(sellerName);
        sb.append(", remakerScore=").append(remakerScore);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}