package com.candy.basic.form;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SellerForm implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.seller_id
     *
     * @mbggenerated
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.seller_name
     *
     * @mbggenerated
     */
    private String sellerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.remaker_score
     *
     * @mbggenerated
     */
    private BigDecimal remakerScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.disable
     *
     * @mbggenerated
     */
    private Short disable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seller
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.seller_id
     *
     * @return the value of seller.seller_id
     *
     * @mbggenerated
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.seller_id
     *
     * @param sellerId the value for seller.seller_id
     *
     * @mbggenerated
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.seller_name
     *
     * @return the value of seller.seller_name
     *
     * @mbggenerated
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.seller_name
     *
     * @param sellerName the value for seller.seller_name
     *
     * @mbggenerated
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName == null ? null : sellerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.remaker_score
     *
     * @return the value of seller.remaker_score
     *
     * @mbggenerated
     */
    public BigDecimal getRemakerScore() {
        return remakerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.remaker_score
     *
     * @param remakerScore the value for seller.remaker_score
     *
     * @mbggenerated
     */
    public void setRemakerScore(BigDecimal remakerScore) {
        this.remakerScore = remakerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.create_date
     *
     * @return the value of seller.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.create_date
     *
     * @param createDate the value for seller.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.update_date
     *
     * @return the value of seller.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.update_date
     *
     * @param updateDate the value for seller.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.disable
     *
     * @return the value of seller.disable
     *
     * @mbggenerated
     */
    public Short getDisable() {
        return disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.disable
     *
     * @param disable the value for seller.disable
     *
     * @mbggenerated
     */
    public void setDisable(Short disable) {
        this.disable = disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sellerId=").append(sellerId);
        sb.append(", sellerName=").append(sellerName);
        sb.append(", remakerScore=").append(remakerScore);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", disable=").append(disable);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
