package com.candy.basic.form;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * @Classname ShopCreateForm
 * @Description TODO
 * @Author liqb
 * @Date 2021/5/27 22:55
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ShopCreateForm implements Serializable {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shop_name
     *
     * @mbggenerated
     */
    @NotBlank(message = "商铺名不为空")
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.price_par_man
     *
     * @mbggenerated
     */
    @NotNull(message = "均价不为空")
    private Integer priceParMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.latitude
     *
     * @mbggenerated
     */
    @NotNull(message = "纬度不为空")
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.longitude
     *
     * @mbggenerated
     */
    @NotNull(message = "经度不为空")
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.category_id
     *
     * @mbggenerated
     */
    @NotNull(message = "品类ID")
    private Long categoryId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.tags
     *
     * @mbggenerated
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.start_time
     *
     * @mbggenerated
     */
    @NotBlank(message = "商铺开始营业不为空")
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.end_time
     *
     * @mbggenerated
     */
    @NotBlank(message = "商铺结束营业不为空")
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.address
     *
     * @mbggenerated
     */
    @NotBlank(message = "地址不为空")
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.seller_id
     *
     * @mbggenerated
     */
    @NotNull(message = "商户ID不为空")
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.icon_url
     *
     * @mbggenerated
     */
    @NotNull(message = "图标不为空")
    private String iconUrl;

}
