package com.candy.basic.form;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

/**
 * @Classname SysUserForm
 * @Description TODO
 * @Author liqb
 * @Date 2021/1/3 22:37
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class SysUserForm implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.mobile_no
     *
     * @mbggenerated
     */
    private String mobileNo;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.gender
     *
     * @mbggenerated
     */
    private Short gender;

}
